## Project Tasks: Perform the following data wrangling steps using Pandas (and NumPy as needed). Structure your code into clear sections or functions. Make sure to comment your code and report findings.

## 1. Inspect the Data

- Load the CSV into a Pandas DataFrame using `pd.read_csv()`.
- Display the DataFrame’s shape, columns, and a few sample rows using `df.head()`.
- Use `df.info()` and `df.describe()` to summarize data types and statistics.
- Explain the meaning of each column (e.g., *“CRASH_DATE is the date of the collision”*).
- Identify which columns are numerical, categorical (text), or dates.

In [1]:
import pandas as pd
import numpy as np

In [2]:
DF_Row = pd.read_csv("Motor_Vehicle_Collisions_-_Crashes.csv", low_memory=False)

# اعمل نسخة منفصلة للـ ZIP CODE بدون تعديل DF_Row الأصلي
DF_Row["ZIP CODE"] = DF_Row["ZIP CODE"].astype(str)
DF_Row.to_json('collisions_raw.json', orient='records', lines=True)

DF_Row["ZIP CODE"] = pd.to_numeric(DF_Row["ZIP CODE"], errors="coerce").astype("Int64")
DF_Row.to_parquet('collisions_raw.parquet')

DF = DF_Row.copy()

In [3]:
# The DataFrame’s Shape, Columns and a Few Sample Rows
print(f"The Shape OF The DataFrame :\n {DF.shape}\n")
print(f"The Columns OF The DataFrame :\n {DF.columns}\n")
print(f"Few Sample Rows OF The DataFrame :\n {DF.head()}\n")

The Shape OF The DataFrame :
 (2196754, 29)

The Columns OF The DataFrame :
 Index(['CRASH DATE', 'CRASH TIME', 'BOROUGH', 'ZIP CODE', 'LATITUDE',
       'LONGITUDE', 'LOCATION', 'ON STREET NAME', 'CROSS STREET NAME',
       'OFF STREET NAME', 'NUMBER OF PERSONS INJURED',
       'NUMBER OF PERSONS KILLED', 'NUMBER OF PEDESTRIANS INJURED',
       'NUMBER OF PEDESTRIANS KILLED', 'NUMBER OF CYCLIST INJURED',
       'NUMBER OF CYCLIST KILLED', 'NUMBER OF MOTORIST INJURED',
       'NUMBER OF MOTORIST KILLED', 'CONTRIBUTING FACTOR VEHICLE 1',
       'CONTRIBUTING FACTOR VEHICLE 2', 'CONTRIBUTING FACTOR VEHICLE 3',
       'CONTRIBUTING FACTOR VEHICLE 4', 'CONTRIBUTING FACTOR VEHICLE 5',
       'COLLISION_ID', 'VEHICLE TYPE CODE 1', 'VEHICLE TYPE CODE 2',
       'VEHICLE TYPE CODE 3', 'VEHICLE TYPE CODE 4', 'VEHICLE TYPE CODE 5'],
      dtype='str')

Few Sample Rows OF The DataFrame :
    CRASH DATE CRASH TIME   BOROUGH  ZIP CODE  LATITUDE  LONGITUDE  \
0  09/11/2021       2:39       NaN      <NA>       NaN        NaN
1  03/26/2022      11:45       NaN      <NA>       NaN        NaN
2  11/01/2023       1:29  BROOKLYN     11230  40.62179 -73.970024
3  06/29/2022       6:55       NaN      <NA>       NaN        NaN
4  09/21/2022      13:21       NaN      <NA>       NaN        NaN

                 LOCATION           ON STREET NAME CROSS STREET NAME  \
0                     NaN    WHITESTONE EXPRESSWAY         20 AVENUE
1                     NaN  QUEENSBORO BRIDGE UPPER               NaN
2  (40.62179, -73.970024)            OCEAN PARKWAY          AVENUE K
3                     NaN       THROGS NECK BRIDGE               NaN
4                     NaN          BROOKLYN BRIDGE               NaN

  OFF STREET NAME  ...  CONTRIBUTING FACTOR VEHICLE 2  \
0             NaN  ...                    Unspecified
1             NaN  ...                            NaN
2             NaN  ...                    Unspecified
3             NaN  ...                    Unspecified
4             NaN  ...                    Unspecified

   CONTRIBUTING FACTOR VEHICLE 3  CONTRIBUTING FACTOR VEHICLE 4  \
0                            NaN                            NaN
1                            NaN                            NaN
2                    Unspecified                            NaN
3                            NaN                            NaN
4                            NaN                            NaN

   CONTRIBUTING FACTOR VEHICLE 5  COLLISION_ID  \
0                            NaN       4455765
1                            NaN       4513547
2                            NaN       4675373
3                            NaN       4541903
4                            NaN       4566131

                   VEHICLE TYPE CODE 1  VEHICLE TYPE CODE 2  \
0                                Sedan                Sedan
1                                Sedan                  NaN
2                                Moped                Sedan
3                                Sedan        Pick-up Truck
4  Station Wagon/Sport Utility Vehicle                  NaN

   VEHICLE TYPE CODE 3 VEHICLE TYPE CODE 4 VEHICLE TYPE CODE 5
0                  NaN                 NaN                 NaN
1                  NaN                 NaN                 NaN
2                Sedan                 NaN                 NaN
3                  NaN                 NaN                 NaN
4                  NaN                 NaN                 NaN

[5 rows x 29 columns]

In [4]:
# Summarization 
print(f"A lots of Data right ? here is summarize :\n ")
DF.info()
DF.describe()

A lots of Data right ? here is summarize :

<class 'pandas.DataFrame'>
RangeIndex: 2196754 entries, 0 to 2196753
Data columns (total 29 columns):
 #   Column                         Dtype
---  ------                         -----
 0   CRASH DATE                     str
 1   CRASH TIME                     str
 2   BOROUGH                        str
 3   ZIP CODE                       Int64
 4   LATITUDE                       float64
 5   LONGITUDE                      float64
 6   LOCATION                       str
 7   ON STREET NAME                 str
 8   CROSS STREET NAME              str
 9   OFF STREET NAME                str
 10  NUMBER OF PERSONS INJURED      float64
 11  NUMBER OF PERSONS KILLED       float64
 12  NUMBER OF PEDESTRIANS INJURED  int64
 13  NUMBER OF PEDESTRIANS KILLED   int64
 14  NUMBER OF CYCLIST INJURED      int64
 15  NUMBER OF CYCLIST KILLED       int64
 16  NUMBER OF MOTORIST INJURED     int64
 17  NUMBER OF MOTORIST KILLED      int64
 18  CONTRIBUTING FACTOR VEHICLE 1  str
 19  CONTRIBUTING FACTOR VEHICLE 2  str
 20  CONTRIBUTING FACTOR VEHICLE 3  str
 21  CONTRIBUTING FACTOR VEHICLE 4  str
 22  CONTRIBUTING FACTOR VEHICLE 5  str
 23  COLLISION_ID                   int64
 24  VEHICLE TYPE CODE 1            str
 25  VEHICLE TYPE CODE 2            str
 26  VEHICLE TYPE CODE 3            str
 27  VEHICLE TYPE CODE 4            str
 28  VEHICLE TYPE CODE 5            str
dtypes: Int64(1), float64(4), int64(7), str(17)
memory usage: 796.1 MB

,ZIP CODE,LATITUDE,LONGITUDE,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,COLLISION_ID
count,1520825.0,1.956597e+06,1.956597e+06,2.196736e+06,2.196723e+06,2.196754e+06,2.196754e+06,2.196754e+06,2.196754e+06,2.196754e+06,2.196754e+06,2.196754e+06
mean,10843.924146,4.060019e+01,-7.370209e+01,3.251998e-01,1.568245e-03,5.912087e-02,7.766004e-04,2.865728e-02,1.233638e-04,2.329269e-01,6.391248e-04,3.248715e+06
std,552.842065,2.242597e+00,4.177683e+00,7.124330e-01,4.178582e-02,2.491214e-01,2.848692e-02,1.690370e-01,1.114716e-02,6.736136e-01,2.759756e-02,1.508704e+06
min,10000.0,0.000000e+00,-2.013600e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.200000e+01
25%,10309.0,4.066739e+01,-7.397457e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.185309e+06
50%,11207.0,4.072032e+01,-7.392687e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.734660e+06
75%,11237.0,4.076958e+01,-7.386662e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,4.284070e+06
max,11697.0,4.334444e+01,0.000000e+00,4.300000e+01,8.000000e+00,2.700000e+01,6.000000e+00,4.000000e+00,2.000000e+00,4.300000e+01,5.000000e+00,4.833511e+06

In [5]:
#Back to the NYC Open Data TO EXTRACT THE Description of each Column
# To Explain the meaning of each column

Column_Desc = [
    "Occurrence date of collision",
    "Occurrence time of collision",
    "Borough where collision occurred",
    "Postal code of incident occurrence",
    "Latitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)",
    "Longitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)",
    "Latitude , Longitude pair",
    "Street on which the collision occurred",
    "Nearest cross street to the collision",
    "Street address if known",
    "Number of persons injured",
    "Number of persons killed",
    "Number of pedestrians injured",
    "Number of pedestrians killed",
    "Number of cyclists injured",
    "Number of cyclists killed",
    "Number of vehicle occupants injured",
    "Number of vehicle occupants killed",
    "Factors contributing to the collision for designated vehicle 1",
    "Factors contributing to the collision for designated vehicle 2",
    "Factors contributing to the collision for designated vehicle 3",
    "Factors contributing to the collision for designated vehicle 4",
    "Factors contributing to the collision for designated vehicle 5",
    "Unique record code generated by system. Primary Key for Crash table.",
    "Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 1",
    "Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 2",
    "Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 3",
    "Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 4",
    "Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 5"
]
# Put the Column name in a list 
Column_Name = list(DF.columns)
# map between Column name and Column Description in Dictionary (Key : value pair)
Column_Meaning = dict(zip(Column_Name,Column_Desc))
print("The Meaning of Each Column : \n")
Column_Meaning

The Meaning of Each Column :

{'CRASH DATE': 'Occurrence date of collision',
 'CRASH TIME': 'Occurrence time of collision',
 'BOROUGH': 'Borough where collision occurred',
 'ZIP CODE': 'Postal code of incident occurrence',
 'LATITUDE': 'Latitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)',
 'LONGITUDE': 'Longitude coordinate for Global Coordinate System, WGS 1984, decimal degrees (EPSG 4326)',
 'LOCATION': 'Latitude , Longitude pair',
 'ON STREET NAME': 'Street on which the collision occurred',
 'CROSS STREET NAME': 'Nearest cross street to the collision',
 'OFF STREET NAME': 'Street address if known',
 'NUMBER OF PERSONS INJURED': 'Number of persons injured',
 'NUMBER OF PERSONS KILLED': 'Number of persons killed',
 'NUMBER OF PEDESTRIANS INJURED': 'Number of pedestrians injured',
 'NUMBER OF PEDESTRIANS KILLED': 'Number of pedestrians killed',
 'NUMBER OF CYCLIST INJURED': 'Number of cyclists injured',
 'NUMBER OF CYCLIST KILLED': 'Number of cyclists killed',
 'NUMBER OF MOTORIST INJURED': 'Number of vehicle occupants injured',
 'NUMBER OF MOTORIST KILLED': 'Number of vehicle occupants killed',
 'CONTRIBUTING FACTOR VEHICLE 1': 'Factors contributing to the collision for designated vehicle 1',
 'CONTRIBUTING FACTOR VEHICLE 2': 'Factors contributing to the collision for designated vehicle 2',
 'CONTRIBUTING FACTOR VEHICLE 3': 'Factors contributing to the collision for designated vehicle 3',
 'CONTRIBUTING FACTOR VEHICLE 4': 'Factors contributing to the collision for designated vehicle 4',
 'CONTRIBUTING FACTOR VEHICLE 5': 'Factors contributing to the collision for designated vehicle 5',
 'COLLISION_ID': 'Unique record code generated by system. Primary Key for Crash table.',
 'VEHICLE TYPE CODE 1': 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 1',
 'VEHICLE TYPE CODE 2': 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 2',
 'VEHICLE TYPE CODE 3': 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 3',
 'VEHICLE TYPE CODE 4': 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 4',
 'VEHICLE TYPE CODE 5': 'Type of vehicle based on the selected vehicle category (ATV, bicycle, car/suv, ebike, escooter, truck/bus, motorcycle, other) for vehicle 5'}

In [6]:
def CheckType(df: pd.DataFrame):
    Numerical = df.select_dtypes(include="number").columns.tolist()
    obj_cols = df.select_dtypes(include="object").columns.tolist()
    Date, Categorical = [], []
    for col in obj_cols:
        try:
            pd.to_datetime(df[col], errors="raise", format="%m/%d/%Y")
            Date.append(col)
            continue
        except Exception:
            pass
        try:
            pd.to_datetime(df[col], errors="raise", format="%H:%M")
            Date.append(col)
            continue
        except Exception:
            pass
        Categorical.append(col)
    return Numerical, Categorical, Date

Numerical, Categorical, Dates = CheckType(DF)

C:\Users\kml_o\AppData\Local\Temp\ipykernel_22428\2723263866.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = df.select_dtypes(include="object").columns.tolist()

## 2. Handle Missing Values

1. **Check for null values:**  
   Use:
   ```python
   df.isnull().sum()
 **Focus on key columns :**
Pay close attention to columns such as:

   ZIP CODE,  CONTRIBUTING FACTOR

   These may contain many blanks.

In [7]:
print(f"Number of NULL Values : \n{DF.isnull().sum()}")

Number of NULL Values :
CRASH DATE                             0
CRASH TIME                             0
BOROUGH                           675613
ZIP CODE                          675929
LATITUDE                          240157
LONGITUDE                         240157
LOCATION                          240157
ON STREET NAME                    476352
CROSS STREET NAME                 838902
OFF STREET NAME                  1812776
NUMBER OF PERSONS INJURED             18
NUMBER OF PERSONS KILLED              31
NUMBER OF PEDESTRIANS INJURED          0
NUMBER OF PEDESTRIANS KILLED           0
NUMBER OF CYCLIST INJURED              0
NUMBER OF CYCLIST KILLED               0
NUMBER OF MOTORIST INJURED             0
NUMBER OF MOTORIST KILLED              0
CONTRIBUTING FACTOR VEHICLE 1       7667
CONTRIBUTING FACTOR VEHICLE 2     350734
CONTRIBUTING FACTOR VEHICLE 3    2037979
CONTRIBUTING FACTOR VEHICLE 4    2160538
CONTRIBUTING FACTOR VEHICLE 5    2186842
COLLISION_ID                           0
VEHICLE TYPE CODE 1                15752
VEHICLE TYPE CODE 2               437504
VEHICLE TYPE CODE 3              2044099
VEHICLE TYPE CODE 4              2161842
VEHICLE TYPE CODE 5              2187150
dtype: int64

2. **Choose a handling strategy**
Examples:

Drop rows missing critical information (e.g., no borough or no coordinates)

Fill missing numeric values with 0

Replace empty categories with "Unknown"

In [8]:
#Drop missing Critical Information
Critical_Info = ['BOROUGH', 'LATITUDE','LONGITUDE']
DF = DF.dropna(subset=Critical_Info)

# Fill Missing Numeric Value with 0 
Num_cols = DF.select_dtypes(include="number").columns
DF[Num_cols] = DF[Num_cols].fillna(0)

# Replace Missing Categorical Value With UnKnown
Cat_cols = DF.select_dtypes(include="object").columns
DF[Cat_cols] = DF[Cat_cols].fillna("Unknown")
DF[Dates]

C:\Users\kml_o\AppData\Local\Temp\ipykernel_22428\689140796.py:10: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  Cat_cols = DF.select_dtypes(include="object").columns

         CRASH DATE CRASH TIME
2        11/01/2023       1:29
9        09/11/2021       9:35
10       12/14/2021       8:13
13       12/14/2021       8:17
14       12/14/2021      21:10
...             ...        ...
2196745  07/31/2025      13:22
2196746  08/05/2025      19:50
2196747  08/05/2025       0:39
2196749  08/05/2025      18:55
2196752  08/05/2025      11:28

[1483413 rows x 2 columns]

4. **Document your reasoning**
Explain why you chose each method for handling missing values.

5. **Apply using Pandas**

               dropna() — remove rows/columns with missing values

               fillna() — replace missing values

               Conditional filtering — keep/remove rows based on conditions
* Answer :         

Coordinates & borough are essential for location-based analysis, so rows missing them are removed.

Numeric casualty counts default to 0 when missing.

Missing category names are set to "Unknown" for clarity.

### 3. Correct Data Types

Ensure each column has an appropriate dtype.

 Parse date/time columns into `datetime64` (e.g. `pd.to_datetime` on `CRASH_DATE` and/or `CRASH_TIME`).

Numeric columns (like `NUMBER OF PERSONS INJURED`) may have been read as floats if NaNs were present; convert them to integers if appropriate (e.g. `df[col] = df[col].astype('Int64')`). 

Convert true/false flags or small categorical columns to category dtype if useful. Verify with `df.dtypes` that types make sense.

In [9]:
print(f"The Date/Time Column :\n{Dates}\n\nAnd The DataType of Each :\n{DF[Dates].dtypes}")
print("\nLet's Convert The DataType to 'datetime64'")

for Col_D in Dates:
    if Col_D in DF.columns:
        n_nat = DF[Col_D].isna().sum()
        print(f"{Col_D}: {n_nat} missing values before conversion")
        
        if Col_D == "CRASH DATE":
            # Convert date in MM/DD/YYYY format
            DF[Col_D] = pd.to_datetime(DF[Col_D], errors='coerce', format="%m/%d/%Y")
        elif Col_D == "CRASH TIME":
            # Convert time in HH:MM format to time objects
            DF[Col_D] = pd.to_datetime(DF[Col_D], errors='coerce', format="%H:%M")

print(f"\nAfter Conversion :\n{DF[Dates].dtypes}")

The Date/Time Column :
['CRASH DATE', 'CRASH TIME']

And The DataType of Each :
CRASH DATE    str
CRASH TIME    str
dtype: object

Let's Convert The DataType to 'datetime64'
CRASH DATE: 0 missing values before conversion
CRASH TIME: 0 missing values before conversion

After Conversion :
CRASH DATE    datetime64[us]
CRASH TIME    datetime64[us]
dtype: object

In [10]:
print(f"The Numerical Column :\n {DF[Numerical].dtypes}")
print("\nLet's Convert The DataType to 'Int64'")

# Columns that should stay as float (continuous values, not counts)
exclude_from_int = ["LATITUDE", "LONGITUDE"]

for Col_N in Numerical:
    if Col_N in DF.columns and Col_N not in exclude_from_int and DF[Col_N].dtype == float:
        DF[Col_N] = DF[Col_N].astype("Int64")

print(f"\nAfter Conversion :\n{DF[Numerical].dtypes} ")

The Numerical Column :
 ZIP CODE                           Int64
LATITUDE                         float64
LONGITUDE                        float64
NUMBER OF PERSONS INJURED        float64
NUMBER OF PERSONS KILLED         float64
NUMBER OF PEDESTRIANS INJURED      int64
NUMBER OF PEDESTRIANS KILLED       int64
NUMBER OF CYCLIST INJURED          int64
NUMBER OF CYCLIST KILLED           int64
NUMBER OF MOTORIST INJURED         int64
NUMBER OF MOTORIST KILLED          int64
COLLISION_ID                       int64
dtype: object

Let's Convert The DataType to 'Int64'

After Conversion :
ZIP CODE                           Int64
LATITUDE                         float64
LONGITUDE                        float64
NUMBER OF PERSONS INJURED          Int64
NUMBER OF PERSONS KILLED           Int64
NUMBER OF PEDESTRIANS INJURED      int64
NUMBER OF PEDESTRIANS KILLED       int64
NUMBER OF CYCLIST INJURED          int64
NUMBER OF CYCLIST KILLED           int64
NUMBER OF MOTORIST INJURED         int64
NUMBER OF MOTORIST KILLED          int64
COLLISION_ID                       int64
dtype: object

### 4. Clean Text/Categorical Data  

Clean up string fields to standardize values. For example:  

- Strip leading/trailing spaces and convert borough names and factor descriptions to consistent case  
  (e.g., `.str.strip().str.title()` or `.str.upper()`).  

- Fix obvious anomalies:  
  - Change `"0"` to missing  
  - Replace `"Unspecified"` with `NaN`  
  - Correct known typos  

- If needed, combine similar categories (e.g., multiple ways of naming the same factor).  

 Show examples of **before/after** for a couple of fields to illustrate the cleaning process.

In [11]:
print(F"Before Cleaning :\n")
DF[Categorical].head()

Before Cleaning :

,BOROUGH,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
2,BROOKLYN,"(40.62179, -73.970024)",OCEAN PARKWAY,AVENUE K,Unknown,Unspecified,Unspecified,Unspecified,Unknown,Unknown,Moped,Sedan,Sedan,Unknown,Unknown
9,BROOKLYN,"(40.667202, -73.8665)",Unknown,Unknown,1211 LORING AVENUE,Unspecified,Unknown,Unknown,Unknown,Unknown,Sedan,Unknown,Unknown,Unknown,Unknown
10,BROOKLYN,"(40.683304, -73.917274)",SARATOGA AVENUE,DECATUR STREET,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
13,BRONX,"(40.86816, -73.83148)",Unknown,Unknown,344 BAYCHESTER AVENUE,Unspecified,Unspecified,Unknown,Unknown,Unknown,Sedan,Sedan,Unknown,Unknown,Unknown
14,BROOKLYN,"(40.67172, -73.8971)",Unknown,Unknown,2047 PITKIN AVENUE,Driver Inexperience,Unspecified,Unknown,Unknown,Unknown,Sedan,Unknown,Unknown,Unknown,Unknown

In [12]:
for Col1 in Categorical : 
 DF[Col1] = DF[Col1].str.strip().str.title()
 DF[Col1] = DF[Col1].replace({
  "0" : np.nan,
  "Unspecified" :np.nan
 })
print("After Cleaning :\n")
DF[Categorical].head()

After Cleaning :

,BOROUGH,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
2,Brooklyn,"(40.62179, -73.970024)",Ocean Parkway,Avenue K,Unknown,NaN,NaN,NaN,Unknown,Unknown,Moped,Sedan,Sedan,Unknown,Unknown
9,Brooklyn,"(40.667202, -73.8665)",Unknown,Unknown,1211 Loring Avenue,NaN,Unknown,Unknown,Unknown,Unknown,Sedan,Unknown,Unknown,Unknown,Unknown
10,Brooklyn,"(40.683304, -73.917274)",Saratoga Avenue,Decatur Street,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
13,Bronx,"(40.86816, -73.83148)",Unknown,Unknown,344 Baychester Avenue,NaN,NaN,Unknown,Unknown,Unknown,Sedan,Sedan,Unknown,Unknown,Unknown
14,Brooklyn,"(40.67172, -73.8971)",Unknown,Unknown,2047 Pitkin Avenue,Driver Inexperience,NaN,Unknown,Unknown,Unknown,Sedan,Unknown,Unknown,Unknown,Unknown

In [24]:
# شوف القيم الفريدة بعمود contributing factor عشان نلاحظ التكرار/التشابه
factor_cols = [c for c in Categorical if "CONTRIBUTING FACTOR" in c]
for col in factor_cols:
    print(f"\n{col}:")
    print(DF[col].value_counts())

CONTRIBUTING FACTOR VEHICLE 1:
CONTRIBUTING FACTOR VEHICLE 1
Driver Inattention/Distraction                           288668
Failure To Yield Right-Of-Way                             94941
Backing Unsafely                                          61890
Following Too Closely                                     48591
Other Vehicular                                           47574
Passing Too Closely                                       39042
Passing Or Lane Usage Improper                            37863
Turning Improperly                                        35366
Traffic Control Disregarded                               27365
Fatigued/Drowsy                                           25710
Driver Inexperience                                       23786
Unsafe Speed                                              18425
Unsafe Lane Changing                                      18065
Alcohol Involvement                                       17239
Lost Consciousness                                        16006
Prescription Medication                                   12854
Pavement Slippery                                         11421
View Obstructed/Limited                                   10520
Oversized Vehicle                                          9400
Reaction To Uninvolved Vehicle                             9321
Pedestrian/Bicyclist/Other Pedestrian Error/Confusion      7912
Outside Car Distraction                                    7873
Physical Disability                                        7711
Aggressive Driving/Road Rage                               7037
Passenger Distraction                                      6689
Unknown                                                    5830
Brakes Defective                                           4607
Fell Asleep                                                3745
Glare                                                      2813
Obstruction/Debris                                         2403
Failure To Keep Right                                      2202
Steering Failure                                           2000
Illness                                                    1876
Other Electronic Device                                    1776
Pavement Defective                                         1486
Tire Failure/Inadequate                                    1222
Illnes                                                     1178
Reaction To Other Uninvolved Vehicle                       1073
Driverless/Runaway Vehicle                                 1017
Animals Action                                              987
Drugs (Illegal)                                             901
Accelerator Defective                                       831
Lane Marking Improper/Inadequate                            631
Traffic Control Device Improper/Non-Working                 619
Cell Phone (Hand-Held)                                      410
Cell Phone (Hands-Free)                                     182
Tow Hitch Defective                                         163
Other Lighting Defects                                      130
Tinted Windows                                              125
Headlights Defective                                        118
Vehicle Vandalism                                           113
Eating Or Drinking                                           79
Using On Board Navigation Device                             71
Windshield Inadequate                                        57
Shoulders Defective/Improper                                 54
80                                                           46
Texting                                                      31
Listening/Using Headphones                                   16
1                                                             3
Name: count, dtype: int64

CONTRIBUTING FACTOR VEHICLE 2:
CONTRIBUTING FACTOR VEHICLE 2
Unknown                                                  250987
Driver Inattention/Distraction                            64606
Other Vehicular                                           23826
Failure To Yield Right-Of-Way                             12585
Passing Or Lane Usage Improper                             7806
Following Too Closely                                      7787
Fatigued/Drowsy                                            6091
Backing Unsafely                                           6073
Passing Too Closely                                        6009
Turning Improperly                                         5915
Traffic Control Disregarded                                5556
Driver Inexperience                                        4919
Lost Consciousness                                         4066
Unsafe Speed                                               3626
Unsafe Lane Changing                                       3234
Prescription Medication                                    2527
Pavement Slippery                                          2385
View Obstructed/Limited                                    2204
Pedestrian/Bicyclist/Other Pedestrian Error/Confusion      1944
Physical Disability                                        1817
Oversized Vehicle                                          1599
Outside Car Distraction                                    1446
Passenger Distraction                                      1237
Reaction To Uninvolved Vehicle                             1169
Alcohol Involvement                                        1167
Aggressive Driving/Road Rage                               1094
Other Electronic Device                                     492
Failure To Keep Right                                       468
Fell Asleep                                                 374
Illness                                                     369
Traffic Control Device Improper/Non-Working                 364
Obstruction/Debris                                          363
Lane Marking Improper/Inadequate                            322
Reaction To Other Uninvolved Vehicle                        300
Glare                                                       294
Brakes Defective                                            259
Pavement Defective                                          110
Drugs (Illegal)                                             109
Steering Failure                                             77
Driverless/Runaway Vehicle                                   68
Cell Phone (Hand-Held)                                       64
Headlights Defective                                         50
Tire Failure/Inadequate                                      50
Accelerator Defective                                        46
Animals Action                                               45
Other Lighting Defects                                       43
Cell Phone (Hands-Free)                                      39
Illnes                                                       30
Tinted Windows                                               26
Tow Hitch Defective                                          22
Vehicle Vandalism                                            12
Eating Or Drinking                                           10
Listening/Using Headphones                                   10
Shoulders Defective/Improper                                  9
80                                                            7
Using On Board Navigation Device                              6
Windshield Inadequate                                         5
Texting                                                       2
Name: count, dtype: int64

CONTRIBUTING FACTOR VEHICLE 3:
CONTRIBUTING FACTOR VEHICLE 3
Unknown                                                  1389620
Other Vehicular                                             1822
Driver Inattention/Distraction                               753
Following Too Closely                                        329
Fatigued/Drowsy                                              246
Pavement Slippery                                            139
Driver Inexperience                                           98
Traffic Control Disregarded                                   86
Failure To Yield Right-Of-Way                                 81
Alcohol Involvement                                           78
Passing Or Lane Usage Improper                                76
Unsafe Speed                                                  61
Backing Unsafely                                              60
Outside Car Distraction                                       51
Fell Asleep                                                   47
Turning Improperly                                            39
Passing Too Closely                                           32
Reaction To Uninvolved Vehicle                                32
Aggressive Driving/Road Rage                                  30
Pedestrian/Bicyclist/Other Pedestrian Error/Confusion         29
Other Electronic Device                                       22
Lost Consciousness                                            21
Unsafe Lane Changing                                          21
Brakes Defective                                              20
Failure To Keep Right                                         19
Prescription Medication                                       18
Obstruction/Debris                                            17
Physical Disability                                           16
Traffic Control Device Improper/Non-Working                   13
Oversized Vehicle                                             11
Drugs (Illegal)                                                9
Passenger Distraction                                          9
Driverless/Runaway Vehicle                                     8
View Obstructed/Limited                                        8
Tire Failure/Inadequate                                        5
Illness                                                        4
Accelerator Defective                                          3
Animals Action                                                 3
Glare                                                          3
Cell Phone (Hands-Free)                                        2
Lane Marking Improper/Inadequate                               2
Pavement Defective                                             2
Steering Failure                                               2
Tinted Windows                                                 2
80                                                             1
Eating Or Drinking                                             1
Reaction To Other Uninvolved Vehicle                           1
Tow Hitch Defective                                            1
Vehicle Vandalism                                              1
Name: count, dtype: int64

CONTRIBUTING FACTOR VEHICLE 4:
CONTRIBUTING FACTOR VEHICLE 4
Unknown                                        1461076
Other Vehicular                                    403
Driver Inattention/Distraction                      76
Following Too Closely                               31
Pavement Slippery                                   31
Fatigued/Drowsy                                     28
Fell Asleep                                         17
Driver Inexperience                                 13
Traffic Control Disregarded                         13
Alcohol Involvement                                 12
Failure To Yield Right-Of-Way                       11
Passing Or Lane Usage Improper                       9
Unsafe Speed                                         9
Backing Unsafely                                     7
Reaction To Uninvolved Vehicle                       7
Obstruction/Debris                                   6
Aggressive Driving/Road Rage                         5
Outside Car Distraction                              5
Brakes Defective                                     4
Drugs (Illegal)                                      4
Other Electronic Device                              4
Passing Too Closely                                  4
Failure To Keep Right                                3
Turning Improperly                                   3
Animals Action                                       2
Lost Consciousness                                   2
Physical Disability                                  2
Tow Hitch Defective                                  2
Traffic Control Device Improper/Non-Working          2
Driverless/Runaway Vehicle                           1
Illness                                              1
Oversized Vehicle                                    1
Prescription Medication                              1
Steering Failure                                     1
Unsafe Lane Changing                                 1
Name: count, dtype: int64

CONTRIBUTING FACTOR VEHICLE 5:
CONTRIBUTING FACTOR VEHICLE 5
Unknown                                        1476991
Other Vehicular                                    126
Driver Inattention/Distraction                      13
Pavement Slippery                                   12
Alcohol Involvement                                  7
Driver Inexperience                                  5
Fell Asleep                                          3
Following Too Closely                                3
Traffic Control Disregarded                          3
Aggressive Driving/Road Rage                         2
Drugs (Illegal)                                      2
Failure To Yield Right-Of-Way                        2
Obstruction/Debris                                   2
Reaction To Uninvolved Vehicle                       2
Animals Action                                       1
Backing Unsafely                                     1
Brakes Defective                                     1
Failure To Keep Right                                1
Fatigued/Drowsy                                      1
Illness                                              1
Oversized Vehicle                                    1
Passing Or Lane Usage Improper                       1
Passing Too Closely                                  1
Steering Failure                                     1
Tow Hitch Defective                                  1
Traffic Control Device Improper/Non-Working          1
Name: count, dtype: int64

In [13]:
print(f"The Categorical Column :\n {DF[Categorical].dtypes}")
print("\nLet's Convert The DataType to 'category'")
for Col_C in Categorical : 
    if Col_C in DF.columns:
        DF[Col_C] = DF[Col_C].astype("category")
print(f"\nAfter Conversion :\n{DF[Categorical].dtypes} ")

The Categorical Column :
 BOROUGH                          str
LOCATION                         str
ON STREET NAME                   str
CROSS STREET NAME                str
OFF STREET NAME                  str
CONTRIBUTING FACTOR VEHICLE 1    str
CONTRIBUTING FACTOR VEHICLE 2    str
CONTRIBUTING FACTOR VEHICLE 3    str
CONTRIBUTING FACTOR VEHICLE 4    str
CONTRIBUTING FACTOR VEHICLE 5    str
VEHICLE TYPE CODE 1              str
VEHICLE TYPE CODE 2              str
VEHICLE TYPE CODE 3              str
VEHICLE TYPE CODE 4              str
VEHICLE TYPE CODE 5              str
dtype: object

Let's Convert The DataType to 'category'

After Conversion :
BOROUGH                          category
LOCATION                         category
ON STREET NAME                   category
CROSS STREET NAME                category
OFF STREET NAME                  category
CONTRIBUTING FACTOR VEHICLE 1    category
CONTRIBUTING FACTOR VEHICLE 2    category
CONTRIBUTING FACTOR VEHICLE 3    category
CONTRIBUTING FACTOR VEHICLE 4    category
CONTRIBUTING FACTOR VEHICLE 5    category
VEHICLE TYPE CODE 1              category
VEHICLE TYPE CODE 2              category
VEHICLE TYPE CODE 3              category
VEHICLE TYPE CODE 4              category
VEHICLE TYPE CODE 5              category
dtype: object

In [14]:
DF.dtypes

CRASH DATE                       datetime64[us]
CRASH TIME                       datetime64[us]
BOROUGH                                category
ZIP CODE                                  Int64
LATITUDE                                float64
LONGITUDE                               float64
LOCATION                               category
ON STREET NAME                         category
CROSS STREET NAME                      category
OFF STREET NAME                        category
NUMBER OF PERSONS INJURED                 Int64
NUMBER OF PERSONS KILLED                  Int64
NUMBER OF PEDESTRIANS INJURED             int64
NUMBER OF PEDESTRIANS KILLED              int64
NUMBER OF CYCLIST INJURED                 int64
NUMBER OF CYCLIST KILLED                  int64
NUMBER OF MOTORIST INJURED                int64
NUMBER OF MOTORIST KILLED                 int64
CONTRIBUTING FACTOR VEHICLE 1          category
CONTRIBUTING FACTOR VEHICLE 2          category
CONTRIBUTING FACTOR VEHICLE 3          category
CONTRIBUTING FACTOR VEHICLE 4          category
CONTRIBUTING FACTOR VEHICLE 5          category
COLLISION_ID                              int64
VEHICLE TYPE CODE 1                    category
VEHICLE TYPE CODE 2                    category
VEHICLE TYPE CODE 3                    category
VEHICLE TYPE CODE 4                    category
VEHICLE TYPE CODE 5                    category
dtype: object

### 5. Filter and Group Data

Demonstrate selection and grouping operations:

- **Filtering:**  
  - Filter the data by date range or borough (e.g., select only collisions in Manhattan).  
  - Explain the subset size after filtering.

- **Grouping and Aggregates:**  
  - Use `groupby` to compute aggregates, for example:  
    - Group by `BOROUGH` to compute the total number of collisions or total injured.  
    - Group by time (year or month) to show trends, such as collisions per year or per month.  

- **Pivot Tables:**  
  - Include a pivot table or grouped results (e.g., counts of collisions by borough and year).

- **Correlation Analysis:**  
  - Compute a correlation matrix of numeric fields (e.g., correlate `NUMBER OF PERSONS INJURED` with `NUMBER OF PEDESTRIANS INJURED`) using Pandas or NumPy (`np.corrcoef`).

In [15]:
Manhattan_coll = DF[DF["BOROUGH"] == "Manhattan"]
print(f"Number of collisions in Manhattan: {len(Manhattan_coll)}")

Number of collisions in Manhattan: 327385

In [16]:
injuries = DF.groupby("BOROUGH").agg(Total_injuries=("NUMBER OF PERSONS INJURED", "sum"))
DF["Year"] = DF["CRASH DATE"].dt.year

# Add Year to the Numerical list so later code that loops over Numerical includes it
if "Year" not in Numerical:
    Numerical.append("Year")

print(f"Collision Per Year :\n {DF.groupby('Year')['CRASH DATE'].count()}")

Collision Per Year :
 Year
2012     77575
2013    155981
2014    156352
2015    163460
2016    136902
2017    138519
2018    144807
2019    133092
2020     71634
2021     70093
2022     66649
2023     64532
2024     64465
2025     39352
Name: CRASH DATE, dtype: int64

In [17]:
Pivot = DF.pivot_table(index="BOROUGH", columns="Year",values="CRASH DATE",aggfunc="count")
Pivot

Year,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
BOROUGH,,,,,,,,,,,,,,
Bronx,9510,19768,19686,21257,19294,20597,22169,21451,13776,12892,11885,10260,9838,5941
Brooklyn,23305,47024,47761,50845,42266,43950,46400,43612,24924,24597,22700,22546,22577,13990
Manhattan,20720,41582,41269,42525,31796,30297,29783,25587,10484,11004,11567,11580,11733,7458
Queens,19138,39312,41022,42490,37598,37622,40459,38931,20140,19040,17868,17485,17658,10342
Staten Island,4902,8295,6614,6343,5948,6053,5996,3511,2310,2560,2629,2661,2659,1621

In [18]:
injury_cols = ["NUMBER OF PERSONS INJURED","NUMBER OF PEDESTRIANS INJURED"]
Correlate = DF[injury_cols].corr()
Correlate

,NUMBER OF PERSONS INJURED,NUMBER OF PEDESTRIANS INJURED
NUMBER OF PERSONS INJURED,1.000000,0.315304
NUMBER OF PEDESTRIANS INJURED,0.315304,1.000000

##  6. Statistical Summaries

- **Numerical Columns**
  - Compute mean, median, min, max, etc.
  - Example: report average injuries per collision.

In [19]:
print(f"Numerical Summary:\n{DF.describe()}")

avg_injuries = DF["NUMBER OF PERSONS INJURED"].mean()
print(f"\nAverage injuries per collision:\n {avg_injuries}")

Numerical Summary:
                       CRASH DATE                  CRASH TIME      ZIP CODE  \
count                     1483413                     1483413     1483413.0
mean   2017-10-24 13:27:53.854280  1900-01-01 13:39:43.895396  10844.038403
min           2012-07-01 00:00:00         1900-01-01 00:00:00           0.0
25%           2014-11-16 00:00:00         1900-01-01 09:48:00       10309.0
50%           2017-05-19 00:00:00         1900-01-01 14:18:00       11207.0
75%           2020-01-20 00:00:00         1900-01-01 18:00:00       11237.0
max           2025-08-05 00:00:00         1900-01-01 23:59:00       11697.0
std                           NaN                         NaN    572.762232

           LATITUDE     LONGITUDE  NUMBER OF PERSONS INJURED  \
count  1.483413e+06  1.483413e+06                  1483413.0
mean   4.059264e+01 -7.368522e+01                   0.309146
min    0.000000e+00 -7.425496e+01                        0.0
25%    4.066669e+01 -7.397605e+01                        0.0
50%    4.071852e+01 -7.392883e+01                        0.0
75%    4.076656e+01 -7.387054e+01                        0.0
max    4.112615e+01  0.000000e+00                       43.0
std    2.298402e+00  4.170500e+00                   0.680941

       NUMBER OF PERSONS KILLED  NUMBER OF PEDESTRIANS INJURED  \
count                 1483413.0                   1.483413e+06
mean                   0.001341                   6.887697e-02
min                         0.0                   0.000000e+00
25%                         0.0                   0.000000e+00
50%                         0.0                   0.000000e+00
75%                         0.0                   0.000000e+00
max                         8.0                   2.700000e+01
std                    0.038636                   2.676993e-01

       NUMBER OF PEDESTRIANS KILLED  NUMBER OF CYCLIST INJURED  \
count                  1.483413e+06               1.483413e+06
mean                   7.408591e-04               3.252297e-02
min                    0.000000e+00               0.000000e+00
25%                    0.000000e+00               0.000000e+00
50%                    0.000000e+00               0.000000e+00
75%                    0.000000e+00               0.000000e+00
max                    6.000000e+00               4.000000e+00
std                    2.806242e-02               1.794662e-01

       NUMBER OF CYCLIST KILLED  NUMBER OF MOTORIST INJURED  \
count              1.483413e+06                1.483413e+06
mean               1.233642e-04                2.027082e-01
min                0.000000e+00                0.000000e+00
25%                0.000000e+00                0.000000e+00
50%                0.000000e+00                0.000000e+00
75%                0.000000e+00                0.000000e+00
max                2.000000e+00                4.300000e+01
std                1.116679e-02                6.299847e-01

       NUMBER OF MOTORIST KILLED  COLLISION_ID          Year
count               1.483413e+06  1.483413e+06  1.483413e+06
mean                4.509870e-04  3.076634e+06  2.017302e+03
min                 0.000000e+00  2.200000e+01  2.012000e+03
25%                 0.000000e+00  2.825717e+06  2.014000e+03
50%                 0.000000e+00  3.677180e+06  2.017000e+03
75%                 0.000000e+00  4.277489e+06  2.020000e+03
max                 5.000000e+00  4.833508e+06  2.025000e+03
std                 2.299961e-02  1.644897e+06  3.541728e+00

Average injuries per collision:
 0.30914586834549784

- **Categorical Columns**
  - Use `.value_counts()` to show top categories.
  - Example: borough with the most crashes.

In [20]:
print(f"\nTop borough by crashes:\n {DF['BOROUGH'].value_counts().head(5)}")

Top borough by crashes:
 BOROUGH
Brooklyn         476497
Queens           399105
Manhattan        327385
Bronx            218324
Staten Island     62102
Name: count, dtype: int64

- **Derived Statistics**
  - Compute simple derived measures (e.g., percentage of crashes with any injuries).

In [21]:
Total_Crashes = DF.shape[0]
Injuries = DF[DF["NUMBER OF PERSONS INJURED"] > 0].shape[0]
Percentage_injuries= (Injuries / Total_Crashes) * 100
print(f"\nPercentage of crashes with injuries: {Percentage_injuries:.2f}%")

Percentage of crashes with injuries: 23.50%

## 7. Export Raw and Cleaned Data

- **Raw Data:**  
  Save the initially loaded DataFrame to **JSON** and **Parquet** formats.  

- **Cleaned/Filtered Data:**  
  Save the cleaned or filtered DataFrame similarly.  

- **Notes:**  
  - Use `orient='records'` and `lines=True` for JSON.  
  - Parquet can use default options.  
  - Ensure all records are included and can be read back by Pandas.

In [22]:
#Save The Row Data Already Done At the Beginning 
# Save cleaned DataFrame (example: DF_clean)
DF.to_json('collisions_clean.json', orient='records', lines=True)
DF.to_parquet('collisions_clean.parquet')

C:\Users\kml_o\AppData\Local\Temp\ipykernel_22428\2896748340.py:3: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  DF.to_json('collisions_clean.json', orient='records', lines=True)

In [23]:
Test_Parquet = pd.read_parquet("collisions_clean.parquet")
print(f"Original: {DF.shape[0]} rows | After reading back: {Test_Parquet.shape[0]} rows")
assert DF.shape[0] == Test_Parquet.shape[0], "Row count mismatch!"
Test_Parquet.head()

Original: 1483413 rows | After reading back: 1483413 rows

,CRASH DATE,CRASH TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5,Year
2,2023-11-01,1900-01-01 01:29:00,Brooklyn,11230,40.621790,-73.970024,"(40.62179, -73.970024)",Ocean Parkway,Avenue K,Unknown,...,NaN,Unknown,Unknown,4675373,Moped,Sedan,Sedan,Unknown,Unknown,2023
9,2021-09-11,1900-01-01 09:35:00,Brooklyn,11208,40.667202,-73.866500,"(40.667202, -73.8665)",Unknown,Unknown,1211 Loring Avenue,...,Unknown,Unknown,Unknown,4456314,Sedan,Unknown,Unknown,Unknown,Unknown,2021
10,2021-12-14,1900-01-01 08:13:00,Brooklyn,11233,40.683304,-73.917274,"(40.683304, -73.917274)",Saratoga Avenue,Decatur Street,Unknown,...,Unknown,Unknown,Unknown,4486609,Unknown,Unknown,Unknown,Unknown,Unknown,2021
13,2021-12-14,1900-01-01 08:17:00,Bronx,10475,40.868160,-73.831480,"(40.86816, -73.83148)",Unknown,Unknown,344 Baychester Avenue,...,Unknown,Unknown,Unknown,4486660,Sedan,Sedan,Unknown,Unknown,Unknown,2021
14,2021-12-14,1900-01-01 21:10:00,Brooklyn,11207,40.671720,-73.897100,"(40.67172, -73.8971)",Unknown,Unknown,2047 Pitkin Avenue,...,Unknown,Unknown,Unknown,4487074,Sedan,Unknown,Unknown,Unknown,Unknown,2021

## References : 

- **NYC Open Data**: [Motor Vehicle Collisions - Vehicles](https://data.cityofnewyork.us/Public-Safety/Motor-Vehicle-Collisions-Vehicles/bm4k-52h4/about_data)  
- **Pandas Documentation**: [Pandas Official Docs](https://pandas.pydata.org/docs/index.html)